#!/usr/bin/python3

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from termcolor import colored
import os
import datetime
from selenium.common.exceptions import TimeoutException

#Configurar segun gustos
cantidadArticulosPantalla=2

#oculta el navegador Firefox
os.environ['MOZ_HEADLESS'] = '1'

#oculta el navegador en Chrome
chrome_options = Options()
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--no-sandbox") # linux only
chrome_options.add_argument("--headless")

# Seleccionar uno comentando o descomentando
#driver = webdriver.Firefox()
driver = webdriver.Chrome(options=chrome_options)


#Obteniendo los datos
try:
    driver.get("https://old.meneame.net")
    noticias = driver.find_elements(By.XPATH, '//*/div/*/h2/a')
    enlaces = driver.find_elements(By.XPATH, '//*/div/*/h2/a[@href]')
    contenidos = driver.find_elements(By.CLASS_NAME, "news-content")
except TimeoutException as ex:
    print("Error de timeout")
    driver.close()
    driver.quit()
    

cantidad_noticias=len(noticias)
fecha = datetime.datetime.now()
print(colored("- Datos de:" + str(fecha) + "----(Noticias:" + str(cantidad_noticias) + ")----", 'dark_grey'))

contador=1
for entrada in range(cantidad_noticias):
        print(colored(noticias[entrada].text, 'red', attrs=["bold"]))
        print(colored(enlaces[entrada].get_attribute('href'), 'yellow', attrs=["underline"]))
        print(colored(contenidos[entrada].text, 'green'))
        print(colored("---------------------------------", 'blue'))
        if contador % cantidadArticulosPantalla == 0:
            print(colored("******** Fin pagina: " + str(int(contador/cantidadArticulosPantalla)) + "****************", 'light_blue'))
            input("Presione Enter para continuar...")
        contador = contador + 1
driver.quit()
